### ISSUE TITLE
Polyline is not drawn if angle is set

### ISSUE THREAD

**Issue by avanc** [planeworld/planeworld#10]
One polyline is not drawn if body_core->angle is set. This happens also, if angle is set to zero. However, the line is shown if the configuration is removed from the xml.
![image](https://cloud.githubusercontent.com/assets/2905029/13683890/8b0852e2-e709-11e5-9d69-1890e1514258.png)
[earth.xml.txt](https://github.com/planeworld/planeworld/files/167964/earth.xml.txt)
[satellite_example.xml.txt](https://github.com/planeworld/planeworld/files/167965/satellite_example.xml.txt)
[sputnik.xml.txt](https://github.com/planeworld/planeworld/files/167963/sputnik.xml.txt)

Another interesting observation is, that the line is also drawn if the object definition is within the main xml and not as separate file.

**Comment by bfeldpw** [comment]
Didn't test it, but one observation is, that the "line_type" of the polyline is not set in sputnik.xml. It can be

- `line_type=single` which is a single segment
- `line_type=strip` which consists of several segments with begin != end
- `line_type=loop` which consists of several segemnts begin and end node connected

I didn't look up the default value, yet, but behaviour seems to be weird due to undefined state. I will check.

**Comment by bfeldpw** [comment]
As expected, LineType is not initialised in constructor. I commited the corrected version. So please test without any changes in sputnik.xml if the observed behaviour is more consistent. Then test with correct line_type in sputnik.xml.

**Comment by avanc** [comment]
Object is drawn correctly with new version.

**Comment by avanc** [comment]
Same correct behaviour with line_type set.
