### ISSUE TITLE
Clarification on coordinate system

### ISSUE THREAD

**Issue by avanc** [planeworld/planeworld#75]
A short discussion in coordinate system:
* x-axis is to the right
* y-axis is upwards
* angle is counter-clockwise
* angle 0° corresponds to x-axis

If this assumption is correct, than the thruster points to wrong direction (90°)

**Comment by bfeldpw** [comment]
Yes, you are right with the coordinate system and yes, thruster direction is an inconsistency concerning its direction.
It was due to the fact, that thrust works on objects which are in general vehicles. Thus, the 0° direction was oriented towards the objects local front (upwards), which seemed quite intuitive. Nevertheless, I'm totally open to change this for consistency.
